# Generated by Django 4.2.13 on 2024-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0003_alter_newsmodel_intensity_alter_newsmodel_likelihood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='pestle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
