# Generated by Django 4.2.13 on 2024-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0004_alter_newsmodel_country_alter_newsmodel_pestle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
