# Generated by Django 4.2.13 on 2024-06-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0005_alter_newsmodel_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='published',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
    ]
