# Generated by Django 4.2.13 on 2024-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0006_remove_newsmodel_published_newsmodel_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
